# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: home
  url: /
  icon:
- page: 前端
  url: /categories/front/
  icon:
- page: 后端
  url: /categories/back/
  icon:
- page: 工具
  url: /categories/tools/
  icon:
- page: 时间轴
  url: /archives/
  icon:

## favicon
favicon: /favicon.png

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: img/head-img.jpg

# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: false

## 网站公告设置
notification: |-
            <p>jiabin个人博客,仅限交流与学习~ <br/>
            </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/xiaojiabin
 - name: 邮箱
   icon: envelope-o
   href: mailto:2493500671@qq.com
#  - name: 联系QQ
#    icon: qq
#    href: /
#  - name: 微信
#    icon: weixin
#    href: /
#  - name: QQ群
#    icon: users
#    href: /
#  - name: RSS
#    icon: feed
#    href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: false
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
  - Hexo官网: https://hexo.io/zh-cn/


# 主题自定义个性化配置

## 网站宣传语
branding: 阿斌的博客

## 设置banner背景图片
banner:
    img: http://7xpw2b.com1.z0.glb.clouddn.com/hexo-sinppet/img/banner.jpg

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，仅限个人学习与记录。'

## 文章内声明
declaration:
  enable: false
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="" target="_blank">Snippet</a>

## 文章打赏
reward:
  alipay: ''
  wepay: ''
  tip: 

## 主题评论

### gitment
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

## Valine评论
valine:
   enable: true
   appId: 9qi0cQkjgVDuBttUnYBUULiJ-gzGzoHsz
   appKey: ktd4f0Ws5cKTGXui3m63jXPt
   placeholder: 说点什么吧
   notify: false
   verify: false
   avatar: mm
   meta: nick,mail
   pageSize: 10

## 网站访客统计
visit_counter:
   site: false
   page: true

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics: 66012954

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: false

#网站主题配置
since: 2018
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1
